import 'car_model.dart';

final List<Car> featuredCars = [
  Car(
    name: "Tesla Model 3",
    brand: "Tesla",
    price: 100,
    image: "assets/tesla_model_3.jpg",
    rating: 4.8,
  ),
  Car(
    name: "BMW M4",
    brand: "BMW",
    price: 150,
    image: "assets/bmw_m4.jpg",
    rating: 4.9,
  ),
  Car(
    name: "Mercedes AMG GT",
    brand: "Mercedes",
    price: 200,
    image: "assets/mercedes_amg.jpg",
    rating: 4.8,
  ),
  Car(
    name: "Audi R8",
    brand: "Audi",
    price: 180,
    image: "assets/audi_r8.jpg",
    rating: 4.7,
  ),
  Car(
    name: "Lamborghini Huracan",
    brand: "Lamborghini",
    price: 300,
    image: "assets/lamborghini_huracan.jpg",
    rating: 4.9,
  ),
  Car(
    name: "Porsche 911",
    brand: "Porsche",
    price: 250,
    image: "assets/porsche_911.jpg",
    rating: 4.8,
  ),
  Car(
    name: "Ford Mustang",
    brand: "Ford",
    price: 120,
    image: "assets/ford_mustang.jpg",
    rating: 4.6,
  ),
  Car(
    name: "Chevrolet Camaro",
    brand: "Chevrolet",
    price: 110,
    image: "assets/chevrolet_camaro.jpg",
    rating: 4.5,
  ),
  Car(
    name: "Nissan GT-R",
    brand: "Nissan",
    price: 220,
    image: "assets/nissan_gtr.jpg",
    rating: 4.7,
  ),
  Car(
    name: "Toyota Supra",
    brand: "Toyota",
    price: 130,
    image: "assets/toyota_supra.jpg",
    rating: 4.6,
  ),
  Car(
    name: "Ferrari 488",
    brand: "Ferrari",
    price: 350,
    image: "assets/ferrari_488.jpg",
    rating: 4.9,
  ),
  Car(
    name: "McLaren 720S",
    brand: "McLaren",
    price: 400,
    image: "assets/mclaren_720s.jpg",
    rating: 5.0,
  ),
  Car(
    name: "Bugatti Chiron",
    brand: "Bugatti",
    price: 900,
    image: "assets/bugatti_chiron.jpg",
    rating: 5.0,
  ),
];
